name: Build and Push Container Image
on:
  create:
    tags:
      - 'v*.*.*'
jobs:
  build-push:
    name: Build and Push Container Image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        images:
          - name: nginx
            file: 8.0-nginx.Dockerfile
          - name: swoole
            file: 8.0-swoole.Dockerfile
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Push
      uses: stafftastic/docker-build-push-action@main
      with:
        name: ${{matrix.images.name}}
        file: ${{matrix.images.file}}
        project: stafftastic
        repository: base-images
        serviceAccountKey: ${{secrets.GOOGLE_ARTIFACT_REGISTRY_SA_KEY}}
